spring:
  rabbitmq:
    addresses: localhost:5672

optilead:
  username: '{cipher}AQAIyOSDmWmWAWdNBs+zHzWODpFTnzdeI4RlK92BZmpIZpa2IiiWyvzdel3TaX3g05V+wqIAUlh0GnGANokYZkGmKcjGKSsoLgsi8amrQV7+q6aoSU7pAuhp+hm6L7+UeVd0U14Ohy/yADSuVgLpxiSFDvBu6t0R+G4fpbjI4Qdx7DcXr1B5H1pAOzgLX9FvJw3IVhKPWIHjeGWm5yN6v/4lTqwF3pCAmqgBDI/VRGWxmaae+WJlC8kGaY9WaYYDTddljgpv18eRPUodk/RE0Wf8GUy57CYCB8GL5oloyFIGGhdjiLc9BVhcXWcV+Bkrqn6UA74BqtZFt4aUANQOV5tZ9nmOOPf7FMyfIHAmxX9SOcHomtTHPC4k6eoI3oQyldA='
  password: '{cipher}AQAIyOSDmWmWAWdNBs+zHzWODpFTnzdeI4RlK92BZmpIZpa2IiiWyvzdel3TaX3g05V+wqIAUlh0GnGANokYZkGmKcjGKSsoLgsi8amrQV7+q6aoSU7pAuhp+hm6L7+UeVd0U14Ohy/yADSuVgLpxiSFDvBu6t0R+G4fpbjI4Qdx7DcXr1B5H1pAOzgLX9FvJw3IVhKPWIHjeGWm5yN6v/4lTqwF3pCAmqgBDI/VRGWxmaae+WJlC8kGaY9WaYYDTddljgpv18eRPUodk/RE0Wf8GUy57CYCB8GL5oloyFIGGhdjiLc9BVhcXWcV+Bkrqn6UA74BqtZFt4aUANQOV5tZ9nmOOPf7FMyfIHAmxX9SOcHomtTHPC4k6eoI3oQyldA='
  endpoint: https://secure.optilead.co.uk
 
server:
  servlet-path: /management
  port: ${port:9090} 

eureka:
  instance:
    statusPageUrlPath: ${server.servlet-path}/info
    healthCheckUrlPath: ${server.servlet-path}/health
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

logging:
  level:
    org.springframework.web: 'DEBUG'
    project.user.UserClient: 'BASIC'
