spring:
  rabbitmq:
    addresses: localhost:5672

ribbon:
  eureka:
   enabled: false

cqEmailTemplateRepository:
  ribbon:
    listOfServers: 10.224.70.15:9001

server:
  servlet-path: /management
  port: ${port:7071}

eureka:
  instance:
    statusPageUrlPath: ${server.servlet-path}/info
    healthCheckUrlPath: ${server.servlet-path}/health
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
