spring:
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: ${jdbc.url:jdbc:oracle:thin:@localhost:1521:xe}
    username: ${jdbc.username:system}
    password: ${jdbc.password:oracle}
    testOnBorrow: true
    validationQuery: SELECT 1 FROM DUAL
    maxWait: 1000
  rabbitmq:
    addresses: localhost:5672
    username: '{cipher}AQCGA4Bf7t7XCrNzW0EcGHNmlEipv32uxr+o4oYLHWV/9Ygp95s632cdvdA2PDFPVr2zY+YK+CwPzWvAJ4veLEO1uln37m2pF95Nz2+MKr53IwBa5kA7zH6qR/EjqymULfbHGBClgn1Eq1OybL5Ph4XwHaIc5hUoaJ73zfilsXzePVez+Hh/1/dxlV5DIIAARCUUrY//UzF+ez/Ac7E5c+YeMkLWOnASNiXtdVGPccIQnyiy94n9JpPCwS63vFkzE3+mxUfBip2/pYpbxBUAHGrpTwiOwFF/aQPAMeiaQwouUSIp0D1K9G8fjKCeQlg9EYJ1B3r66YkUvaRNXn0+16BP8timHe9njlfcyjI1bZaRRWsARDhBOqIH2gwW7g1dGv4='
    password: '{cipher}AQCGA4Bf7t7XCrNzW0EcGHNmlEipv32uxr+o4oYLHWV/9Ygp95s632cdvdA2PDFPVr2zY+YK+CwPzWvAJ4veLEO1uln37m2pF95Nz2+MKr53IwBa5kA7zH6qR/EjqymULfbHGBClgn1Eq1OybL5Ph4XwHaIc5hUoaJ73zfilsXzePVez+Hh/1/dxlV5DIIAARCUUrY//UzF+ez/Ac7E5c+YeMkLWOnASNiXtdVGPccIQnyiy94n9JpPCwS63vFkzE3+mxUfBip2/pYpbxBUAHGrpTwiOwFF/aQPAMeiaQwouUSIp0D1K9G8fjKCeQlg9EYJ1B3r66YkUvaRNXn0+16BP8timHe9njlfcyjI1bZaRRWsARDhBOqIH2gwW7g1dGv4='
  redis:
    sentinel:
      master: mymaster
      nodes: localhost:26379

services:
  energy: energy-v1

memcached:
  addresses: localhost:11211

cqServerUrl: http://localhost:51001

webservice:
  authentication:
    username: ONLSRVUSER
    password: usatoday1
  personalProjection:
    caller:
      endpoint: http://193.67.163.82/tpicxtmqa/XISOAPAdapter/MessageServlet?senderParty=Online&senderService=BSR_WebService_PI&receiverParty=&receiverService=&interface=QueryProductTariffsOut&interfaceNamespace=urn%3Abritishgas.co.uk%3AEnterprise%3AProduct
      expiry: 3600

cache:
  tariffs:
    expiry: -1
  quotes:
    expiry: 3600

server:
  port: 9092
  servlet-path: /management

eureka:
  instance:
    statusPageUrlPath: ${server.servlet-path}/info
    healthCheckUrlPath: ${server.servlet-path}/health
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 30000

logging:
  level:
    root: INFO
    org.springframework.ws.client.MessageTracing.sent: 'TRACE'
    org.springframework.ws.client.MessageTracing.received: 'TRACE'
