server:
  port: ${port:8761}

management:
  port: ${port:8861}
    
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    hostname: localhost
    securePort: ${server.port}
    securePortEnabled: true  
    nonSecurePortEnabled: false 

spring:
  rabbitmq:
    addresses: localhost:5672

logging:
  level:
    org.springframework:
      cloud: 'DEBUG'
      web: 'DEBUG'
