server:
  port: 9543

spring:
  redis:
    sentinel:
      master: mymaster
      nodes: localhost:26379
      
eureka:
  instance:
    statusPageUrlPath: ${server.servlet-path}/info
    healthCheckUrlPath: ${server.servlet-path}/health
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

services:
  energy: energy-v1

webservice:
  authentication:
    username: ONLSRVUSER
    password: usatoday1

payments.financial.transactions.caller:
  endpoint: http://193.67.163.82/tpicxtmqa/XISOAPAdapter/MessageServlet?senderParty=Online&senderService=BSR_WebService_PI&receiverParty=&receiverService=&interface=QueryCustomerAccount&interfaceNamespace=urn%3Abritishgas.co.uk%3AEnterprise%3AFinancialTransaction
#  endpoint: http://localhost:50001/
  expiry: 3600
bill.document.caller:
  endpoint: http://193.67.163.82/docvlwebx001/icp/ICVService
  expiry: 3600
  
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 30000


logging.level:
  root: INFO
  org.springframework.ws.client.MessageTracing.sent: TRACE
  org.springframework.ws.client.MessageTracing.received: TRACE
  org.springframework.ws.client.core: TRACE
