server:
  port: 9543

spring:
  redis:
    sentinel:
      master: mymaster
      nodes: localhost:26379
      
eureka:
  instance:
    statusPageUrlPath: ${server.servlet-path}/info
    healthCheckUrlPath: ${server.servlet-path}/health
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

services:
  energy-accounts: energy-accounts-v1

webservice:
  authentication:
    username: ONLSRVUSER
    password: usatoday1

payments.financial.transactions.caller:
  endpoint: http://tpicxtmqa.uk.centricaplc.com:50000/XISOAPAdapter/MessageServlet?senderParty=Online&senderService=BSR_WebService_PI&receiverParty=&receiverService=&interface=QueryCustomerAccount&interfaceNamespace=urn%3Abritishgas.co.uk%3AEnterprise%3AFinancialTransaction
  expiry: 3600
