spring:
  rabbitmq:
    addresses: localhost:5672
 
  redis:
    sentinel:
      master: mymaster
      nodes: localhost:26379
    
memcached:
  addresses: localhost:22121

server:
  servlet-path: /management

management:
  port: 9140

cqServerUrl: https://localhost

smart:
  survey:
    caller:
      endpoint: http://10.224.70.15/tpicxtmqa/XISOAPAdapter/MessageServlet?senderParty=Online&senderService=BSR_WebService_PI&receiverParty=&receiverService=&interface=SmartMeterProcessingReadLeadOut&interfaceNamespace=urn%3Abritishgas.co.uk%3AOnline%3ASmartMeterProcessing
      expiry: 3600
      
  updatesurvey:
    caller:
      endpoint: http://10.224.70.15/tpicxtmqa/XISOAPAdapter/MessageServlet?senderParty=&senderService=BSR_WebService_PI&receiverParty=&receiverService=&interface=SmartMeterProcessingActionMeterOut&interfaceNamespace=urn%3Abritishgas.co.uk%3AOnline%3ASmartMeterProcessing
      expiry: 3600

webservice:
  authentication:
    username: ONLSRVUSER
    password: usatoday1
    
rest:
  cid: cbdcfa43-dd67-4c38-b418-83572a936fca

ribbon:
  eureka:
   enabled: false

encryption:
  AES:
    cbc-iv: ${aes.iv}
    seed: ${aes.seed}
   
eureka:
  instance:
    metadata-map:
      instanceId: 1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 30000

logging:
  level:
    root: DEBUG
    org.springframework.ws.client.MessageTracing.sent: 'TRACE'
    org.springframework.ws.client.MessageTracing.received: 'TRACE'
---
spring:
  profiles: instance-1

server:
  port: ${port:9030}

management:
  port: 9130

eureka:
  instance:
    metadata-map:
      instanceId: 1
--- 
spring:
  profiles: instance-2

server:
  port: ${port:9031}

management:
  port: 9131


eureka:
  instance:
    metadata-map:
      instanceId: 2
---
spring:
  profiles: instance-3

server:
  port: ${port:9032}

management:
  port: 9132

eureka:
  instance:
    metadata-map:
      instanceId: 3
