spring:
  rabbitmq:
    addresses: localhost:5672
 
  redis:
    sentinel:
      master: mymaster
      nodes: localhost:26379
    
memcached:
  addresses: localhost:22121

server:
  servlet-path: /management

management:
  port: 9140

cqServerUrl: https://localhost

smart:
  survey:
    caller:
      endpoint: http://10.224.70.15/tpicxtmqa/XISOAPAdapter/MessageServlet?senderParty=Online&senderService=BSR_WebService_PI&receiverParty=&receiverService=&interface=SmartMeterProcessingReadLeadOut&interfaceNamespace=urn%3Abritishgas.co.uk%3AOnline%3ASmartMeterProcessing
      expiry: 3600
      
  updatesurvey:
    caller:
      endpoint: http://10.224.70.15/tpicxtmqa/XISOAPAdapter/MessageServlet?senderParty=&senderService=BSR_WebService_PI&receiverParty=&receiverService=&interface=SmartMeterProcessingActionMeterOut&interfaceNamespace=urn%3Abritishgas.co.uk%3AOnline%3ASmartMeterProcessing
      expiry: 3600

webservice:
  authentication:
    username: ONLSRVUSER
    password: usatoday1
    
rest:
  cid: cbdcfa43-dd67-4c38-b418-83572a936fca

ribbon:
  eureka:
   enabled: false

encryption:
  AES:
    cbc-iv: '{cipher}AQAKU4wwwws/qYGn/MwCd/PQnLB4lJRznxMLuqMhC/kIEI20X0yWVTHAEC/6GQ9lo+DIThnEXcXhEgyPuad5VGJsaXAC5/iDjk3FS+mzcY9FQKSvEGuO28GuHYoX2TVvZern6H221IArmhm5UQQqVcn0599dvjx+6nrvui++mbFG8HmsoiEO0TsrgvIiBEXhcBo3yO5yRPRRpWP/O/ddf1snFfCFGvlGvIKdOHyT24tfUjOVr8NFam85+rMLLGuF4b6rENeG+7+fXmnmLRr/o5F51GskpHsTeM+Ck+0ChnpLYj/tHMkhK45z4SLWvWohqKmD18TsI6U1639J3fcAik+Z7dZHL6pW+WccgJpGQIOO7wSvZLOHYiXIkXXI5n+Y4WMs0Y19hTvkYaaU+5Jw+r/B'
    seed: '{cipher}AQBrOvQBzxAYqcd3qR+kOav5hi7W0ITVUZAP4HcmuC8cZR26YawdWNSZxrJz8DYgTUzmgeuEmV2nJr07GltNal/hpOtz+mKUEfwxKuREOWBeDl9POCPrOgU8yt09S2qhSFkHwwfdhFVddULwjJmZxzfvzCF8SHG8/qI7YwpEg+gzT83WAxyY98leVyq+o/IrFXgD7qY2ZfPCFVWOvj/MMKoXPXyg/UMNVwiFDdzYYzPy6upGeOkU3l7/vYlGJdifFihqw3+Q3qm3yoUrhcgJOAdssidd0ZW2zPDrY2fdXZuqvY3jZf/mu7sNQJ4EuVTHcB/wOfuIQqGFlU1D+yHS9kiskpKtyTHUtRFip0XHKVw9QvKzVjAtrXCyVHZCn4UbLvE='
   
eureka:
  instance:
    metadata-map:
      instanceId: 1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 30000

logging:
  level:
    root: DEBUG
    org.springframework.ws.client.MessageTracing.sent: 'TRACE'
    org.springframework.ws.client.MessageTracing.received: 'TRACE'
---
spring:
  profiles: instance-1

server:
  port: ${port:9030}

management:
  port: 9130

eureka:
  instance:
    metadata-map:
      instanceId: 1
--- 
spring:
  profiles: instance-2

server:
  port: ${port:9031}

management:
  port: 9131


eureka:
  instance:
    metadata-map:
      instanceId: 2
---
spring:
  profiles: instance-3

server:
  port: ${port:9032}

management:
  port: 9132

eureka:
  instance:
    metadata-map:
      instanceId: 3
