spring:
  rabbitmq:
    addresses: localhost:5672

redis:
  host: localhost
  port: 26379
 
ribbon:
  eureka:
   enabled: false

cqRepository:
  ribbon:
    listOfServers: localhost:9002

server:
  servlet-path: /management
  port: ${port:9091} 

eureka:
  instance:
    statusPageUrlPath: ${server.servlet-path}/info
    healthCheckUrlPath: ${server.servlet-path}/health
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

logging:
  level:
    org.springframework.web: 'DEBUG'
    project.user.UserClient: 'BASIC'
