spring:
  rabbitmq:
    addresses: localhost:5672
  redis:
    sentinel:
      master: mymaster
      nodes: localhost:26379

ribbon:
  eureka:
   enabled: false

cqRepository:
  ribbon:
    #listOfServers: localhost:1080
    listOfServers: 10.224.70.15:9001
    #listOfServers: 10.224.70.74:9001

server:
  port: ${port:9080}
  servlet-path: /management
  
eureka:
  instance:
    metadata-map:
      instanceId: 1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 30000

logging:
  level:
    com.netflix.discovery: 'DEBUG'
    org.springframework.cloud: 'DEBUG'
    feign: 'DEBUG'
    root: 'DEBUG'
  appender:
    root:
      file: org.apache.log4j.RollingFileAppender
        File: mylogs.log
      layout: org.apache.log4j.PatternLayout
        ConversionPattern: %d{dd-MM-yyyy HH:mm:ss} %-5p %c{1}:%L - %m%n
