spring:
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: ${jdbc.url:jdbc:oracle:thin:@localhost:1521:xe}
    username: ${jdbc.username:system}
    password: ${jdbc.password:oracle}
    testOnBorrow: true
    validationQuery: SELECT 1 FROM DUAL
    maxWait: 1000
  jpa:
    hibernate:
      ddl-auto: none
  redis:
    sentinel:
      master: mymaster
      nodes: localhost:26379

cqServers:
 defaultHost: 'http://localhost:7000'
 servers:
   ? "https://10_114_69_15"
   : {
       name: digital-1, 
       hostnames: [ '10.224.70.15', '193.67.163.82', '10.224.70.29' ]
     }
   ? 'https://10_114_69_17'
   : {
       name: digital-2,
       hostnames: [ '10.224.70.17', '193.67.163.83', '10.224.70.19' ]
     }
   ? 'https://10_114_69_18'
   : {
       name: digital-3,
       hostnames: [ '10.224.70.18', '193.67.163.41', '10.224.70.22' ]
     }
   ? 'https://10_114_69_36'
   : {
       name: digital-5,
       hostnames: [ '10.224.70.36', '193.67.163.50', '10.224.70.38' ]
     }
   ? 'https://10_224_69_37'
   : {
       name: digital-6,
       hostnames: [ '10.224.70.37', '193.67.163.39', '10.224.70.41' ]
     }
   ? 'https://10_114_69_44'
   : {
       name: digital-7,
       hostnames: [ '10.224.70.44', '193.67.163.110', '10.224.70.45' ]
     }
   ? 'https://10_114_69_51'
   : {
       name: digital-8,
       hostnames: [ '10.224.70.51', '193.67.163.22', '10.224.70.52' ]
     }
   ? 'https://10_114_69_55'
   : {
       name: digital-9,
       hostnames: [ '10.224.70.55', '10.224.70.56' ]
     }
   ? 'https://10_114_69_59'
   : {
       name: digital-10,
       hostnames: [ '10.224.70.59', '193.67.161.46', '10.224.70.60' ]
     }
   ? 'https://10_114_69_76'
   : {
       name: digital-11,
       hostnames: [ '10.224.70.76', '193.67.164.24', '10.224.70.77' ]
     }
   ? 'https://10_114_69_75'
   : {
       name: digital-12,
       hostnames: [ '10.224.70.75', '193.67.163.21', '10.224.70.80' ]
     }
   ? 'https://10_114_69_83'
   : {
       name: digital-13,
       hostnames: [ '10.224.70.83', '193.67.163.63', '10.224.70.86' ]
     }
   ? 'https://10_114_69_84'
   : {
       name: digital-14,
       hostnames: [ '10.224.70.84', '193.67.161.47', '10.224.70.89' ]
     }
   ? 'https://10_114_69_33'
   : {
       name: digital-15,
       hostnames: [ '10.224.70.33', '193.67.163.51', '10.224.70.34' ]
     }
   ? 'https://10_114_69_95'
   : {
       name: digital-15,
       hostnames: [ '10.224.70.95', '10.224.70.96' ]
     }
   ? 'https://10_114_69_69'
   : {
       name: digital-17,
       hostnames: [ '10.224.70.69', '10.224.70.68' ]
     }
   ? 'https://10_114_69_104'
   : {
       name: digital-18,
       hostnames: [ '10.224.70.104', '193.67.163.23', '10.224.70.105' ]
     }
   ? 'https://10_114_69_111'
   : {
       name: uat-111,
       hostnames: [ '10.224.70.111', '193.67.163.141', '10.224.70.114' ]
     }
   ? 'https://10_114_69_50'
   : {
       name: uat-50,
       hostnames: [ '10.224.70.50', '193.67.160.93', '10.224.70.63' ]
     }
   ? 'https://10_114_69_74'
   : {
       name: prod-74,
       hostnames: [ '10.224.70.74', '193.67.162.139', '10.224.70.108' ]
     }
   ? 'https://10_114_69_100'
   : {
       name: bot-server,
       hostnames: [ '10.224.70.100' ]
     }
     
eureka:
  instance:
    hostname: localhost
    statusPageUrl: https://${eureka.instance.hostname}/info
    healthCheckUrl: https://${eureka.instance.hostname}/health
    homePageUrl: https://${eureka.instance.hostname}/
    securePortEnabled: true
    securePort: ${server.port}
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

authentication:
  login:
    appUrl: /identity/
    failureUrl: /identity/#/?error=%s
    success: /login

services:
  emails: emails
  audits: audits
  
encryption:
  AES:
    cbc-iv: '{cipher}AQAKU4wwwws/qYGn/MwCd/PQnLB4lJRznxMLuqMhC/kIEI20X0yWVTHAEC/6GQ9lo+DIThnEXcXhEgyPuad5VGJsaXAC5/iDjk3FS+mzcY9FQKSvEGuO28GuHYoX2TVvZern6H221IArmhm5UQQqVcn0599dvjx+6nrvui++mbFG8HmsoiEO0TsrgvIiBEXhcBo3yO5yRPRRpWP/O/ddf1snFfCFGvlGvIKdOHyT24tfUjOVr8NFam85+rMLLGuF4b6rENeG+7+fXmnmLRr/o5F51GskpHsTeM+Ck+0ChnpLYj/tHMkhK45z4SLWvWohqKmD18TsI6U1639J3fcAik+Z7dZHL6pW+WccgJpGQIOO7wSvZLOHYiXIkXXI5n+Y4WMs0Y19hTvkYaaU+5Jw+r/B'
    seed: '{cipher}AQBrOvQBzxAYqcd3qR+kOav5hi7W0ITVUZAP4HcmuC8cZR26YawdWNSZxrJz8DYgTUzmgeuEmV2nJr07GltNal/hpOtz+mKUEfwxKuREOWBeDl9POCPrOgU8yt09S2qhSFkHwwfdhFVddULwjJmZxzfvzCF8SHG8/qI7YwpEg+gzT83WAxyY98leVyq+o/IrFXgD7qY2ZfPCFVWOvj/MMKoXPXyg/UMNVwiFDdzYYzPy6upGeOkU3l7/vYlGJdifFihqw3+Q3qm3yoUrhcgJOAdssidd0ZW2zPDrY2fdXZuqvY3jZf/mu7sNQJ4EuVTHcB/wOfuIQqGFlU1D+yHS9kiskpKtyTHUtRFip0XHKVw9QvKzVjAtrXCyVHZCn4UbLvE='

server:
  port: 9010
  ssl:
    enabled: true
    key-store: ${ssl.keystore:classpath:keystore.jks}
    key-store-password: ${ssl.key-store-password:password12}
    key-alias: ${ssl.key-alias:uaa}

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 30000
