info:
  component: Zuul Server
  
zuul:
  ignoredServices: '*'
  routes:
    addresses: 
      path: /addresses/**
  cors:
    /*:
      allowedOrigins:
        - www.britishgas.co.uk
        - www.example.com
      allowedMethods:
        - GET
        - POST
        - PATCH
        - DELETE
    
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

spring:
  rabbitmq:
    addresses: localhost:5672

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}] [%15.15t] %-40.40logger{39}: %m%n'

server:
  servlet-path: /management
  port: ${port:8771} 
