info:
  component: Zuul Server
  
zuul:
  ignoredServices: '*'
  routes:
    addresses: 
      path: /addresses/**
    callbacks:
      path: /callbacks/**
  cors:
    /*:
      allowedOrigins:
        - www.britishgas.co.uk
        - www.example.com
      allowedMethods:
        - GET
        - POST
        - PATCH
        - DELETE
    
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

spring:
  rabbitmq:
    addresses: localhost:5672

logging:
  level:
    root: INFO

server:
  port: ${port:8771} 
